---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: Doc é o assistente de IA do NetApp disponível no docs.NetApp.com. Ele responde a perguntas usando apenas o conteúdo deste site. O DOC não usa conteúdo de outros sites da NetApp ou da Internet pública para responder a perguntas. 
---
= Visão geral do assistente NetApp generative com IA
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Doc é o assistente de IA do NetApp disponível no docs.NetApp.com. Ele responde a perguntas usando apenas o conteúdo deste site. O DOC não usa conteúdo de outros sites da NetApp ou da Internet pública para responder a perguntas.

O DOC pode criar respostas de perguntas anteriores, sugerir perguntas adicionais e explicar como ele gera respostas. Isso o torna uma ferramenta valiosa para navegar na documentação do NetApp.



== Escopo e limitações

O DOC pode responder apenas a perguntas com base em conteúdo selecionado publicado em docs.NetApp.com.


NOTE: Durante esta fase beta, o Doc não é treinado em todos os conteúdos docs.NetApp.com. O DOC pode responder a perguntas sobre conteúdo, incluindo, entre outros, ONTAP, BlueXP , StorageGRID, Keystone e SnapCenter Content. Se você precisar de informações que o Doc não tem, informe-nos.

* O Doc responde a perguntas com base apenas na versão mais recente publicada de um produto. Por exemplo, se houver documentação para a versão 1.0 e a versão 2.0 de um produto, o Doc se refere apenas à documentação 2.0 mais recente.
* Para melhores resultados, seja sempre específico com os nomes dos produtos. O Doc sabe em que página você está quando faz uma pergunta, mas esse é apenas um dos vários fatores que ele leva em consideração ao formular uma resposta.
* O DOC pode conversar em idiomas compatíveis com docs.NetApp.com, mas não é treinado em versões não inglesas.




== Escrever bons prompts

Siga estas dicas para obter a melhor experiência com o Doc.

Faça perguntas específicas.:: Escreva perguntas detalhadas e especifique o nome do produto, versão e tipo de interface (GUI, API). Por exemplo:
+
--
[]
====
Que passos devo seguir no Gestor de sistema para atualizar do ONTAP 9,8 para o ONTAP 9.12.1?

====
--
Peça etapas para concluir uma tarefa.:: Peça ao Doc para incluir as etapas para concluir um processo. Em vez de perguntar _como eu instalo o BlueXP  Connector sem internet?_ Tente:
+
--
[]
====
Que passos devo seguir para instalar o conetor BlueXP  sem Internet?

====
--
Divida perguntas complexas em pedaços.:: Divida perguntas complexas em perguntas menores (também conhecidas como _encadeamento_). O DOC lembra perguntas anteriores e constrói respostas mais complexas à medida que você continua a conversar.
+
--
Por exemplo, em vez de perguntar Doc _como configuro a proteção contra ransomware e programações de backup no BlueXP ?_ Tente:

[]
====
Quais são as etapas para configurar a proteção contra ransomware no BlueXP ?

====
em seguida, pergunte:

[]
====
Quais são as etapas para configurar agendamentos de backup no BlueXP ?

====
--
Use aspas.:: Inclua frases com várias palavras entre aspas. Isso ajuda Doc a reconhecer a frase como um único conceito, semelhante a como você pode enfatizá-la em uma conversa com um ser humano.
+
--
Por exemplo, nesta pergunta, _como a eficiência de armazenamento é calculada no ONTAP?_ Doc pode pensar que você está perguntando sobre _storage_ e _eficiência_ como duas palavras não relacionadas. Em vez disso, tente:

[]
====
Como é calculada a "eficiência de storage" no ONTAP?

====
--
Reveja como o Doc respondeu.:: Depois de responder, o Doc fornece insights sobre como ele gerou sua resposta. Isso pode lhe dar ideias sobre como refinar sua pergunta para obter os resultados desejados.
Limpe seu histórico de bate-papo:: Se você quiser alterar tópicos, desmarque o chat no início de novo. Como o Doc se lembra de perguntas anteriores, as alterações de tópicos podem produzir resultados inesperados.




== Feedback

O seu feedback ajuda-nos a melhorar a forma como o Doc responde. Use a ferramenta de feedback na janela de bate-papo do Doc para nos informar se as respostas são precisas e úteis ou se precisam de melhorias. Você também pode enviar um e-mail para NetApp.com com com perguntas ou comentários.
