---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: O DOC é o nosso assistente generativo com IA no docs.NetApp.com. O DOC foi projetado para responder a perguntas sobre produtos NetApp, usando conteúdo publicado em docs.NetApp.com. 
---
= Visão geral do assistente NetApp generative com IA
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O DOC é o nosso assistente generativo com IA no docs.NetApp.com. O DOC foi projetado para responder a perguntas sobre produtos NetApp, usando conteúdo publicado em docs.NetApp.com.

O DOC pode criar respostas de perguntas anteriores, sugerir perguntas adicionais e explicar como ele gera respostas. Isso o torna uma ferramenta valiosa para navegar na documentação do NetApp.



== Escopo e limitações

O DOC pode responder apenas a perguntas com base em conteúdo selecionado publicado em docs.NetApp.com.


NOTE: Durante a fase Beta, o Doc usa a maior parte, mas não todo o conteúdo publicado em docs.netapp.com para responder perguntas.  Doc está familiarizado com todos os documentos do ONTAP, NetApp Console, StorageGRID, E-Series, Keystone e SnapCenter e os usa para responder perguntas sobre esses produtos.  Por outro lado, Doc não está familiarizado com a documentação de alguns produtos legados.  Por exemplo, o Doc não usa documentos do SnapDrive for UNIX para fornecer respostas.  Ao longo do Beta, estamos trabalhando para refinar o conhecimento do Doc.  Se precisar de informações que o Doc não tem, envie um e-mail para:ng-doccomments@netapp.com[informe-nos].

* O Doc responde a perguntas com base apenas na versão mais recente publicada de um produto. Por exemplo, se houver documentação para a versão 1.0 e a versão 2.0 de um produto, o Doc se refere apenas à documentação 2.0 mais recente.
* Para melhores resultados, seja sempre específico com os nomes dos produtos. O Doc sabe em que página você está quando faz uma pergunta, mas esse é apenas um dos vários fatores que ele leva em consideração ao formular uma resposta.
* O DOC pode conversar em idiomas compatíveis com docs.NetApp.com, mas não é treinado em versões não inglesas.




== Escrever bons prompts

Siga estas dicas para obter a melhor experiência com o Doc.

Faça perguntas específicas.:: Escreva perguntas detalhadas e especifique o nome do produto, versão e tipo de interface (GUI, API). Por exemplo:
+
--
[]
====
Que passos devo seguir no Gestor de sistema para atualizar do ONTAP 9,8 para o ONTAP 9.12.1?

====
--
Peça etapas para concluir uma tarefa.:: Peça ao Doc para incluir as etapas para concluir um processo.  Em vez de perguntar _Como instalo o agente do NetApp Console sem internet?_ tente:
+
--
[]
====
Quais etapas devo seguir para instalar o agente do NetApp Console sem internet?

====
--
Divida perguntas complexas em pedaços.:: Divida perguntas complexas em perguntas menores (também conhecidas como _encadeamento_). O DOC lembra perguntas anteriores e constrói respostas mais complexas à medida que você continua a conversar.
+
--
Por exemplo, em vez de perguntar ao Doc _Como configuro a proteção contra ransomware e os agendamentos de backup no NetApp Console?_, tente:

[]
====
Quais são as etapas para configurar a proteção contra ransomware no NetApp Console?

====
em seguida, pergunte:

[]
====
Quais são as etapas para configurar agendamentos de backup no NetApp Console?

====
--
Use aspas.:: Inclua frases com várias palavras entre aspas. Isso ajuda Doc a reconhecer a frase como um único conceito, semelhante a como você pode enfatizá-la em uma conversa com um ser humano.
+
--
Por exemplo, nesta pergunta, _como a eficiência de armazenamento é calculada no ONTAP?_ Doc pode pensar que você está perguntando sobre _storage_ e _eficiência_ como duas palavras não relacionadas. Em vez disso, tente:

[]
====
Como é calculada a "eficiência de storage" no ONTAP?

====
--
Reveja como o Doc respondeu.:: Depois de responder, o Doc fornece insights sobre como ele gerou sua resposta. Isso pode lhe dar ideias sobre como refinar sua pergunta para obter os resultados desejados.
Limpe seu histórico de bate-papo:: Se quiser mudar de assunto (por exemplo, se quiser perguntar sobre um produto diferente), limpe o histórico do chat para iniciar uma nova sessão. Se você não limpar o chat antes de iniciar um novo tópico, poderá obter resultados imprecisos.




== Feedback

Estamos trabalhando para melhorar continuamente o Doc. Por favor, envie-nos feedback dentro da janela de bate-papo do Doc. Deixe-nos saber se as respostas do Doc são precisas e úteis ou se estão incompletas ou de alguma forma insuficientes. Você também pode enviar um e-mail para:ng-doccomments at NetApp.com[Contact US] se você tiver alguma dúvida ou preocupação sobre as capacidades ou respostas do Doc.
