---
settings:
  name: About docs.netapp.com
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: pt-br,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Sobre os sites
    url: "/docs-netapp-com.html"
  - title: Sobre o Doc (assistente com IA)
    entries:
    - title: Capacidades e limitações
      url: "/doc-gen-ai-assistant.html"
    - title: Termos de uso
      url: "/doc-gen-ai-assistant-terms-of-use.html"
  - title: Avisos legais
    url: "/legal-notices.html"
